apiVersion: networking.k8s.io/v1beta1
kind: Ingress 
metadata: 
    name: ingress-srv 
    # this step will tell ingress to pick up
    # routing rules mentioned in this file 
    annotations:
        kubernetes.io/ingress.class: nginx 
spec: 
    # our custom routing rules
    rules: 
        - host: posts.com 
          http: 
            paths: 
                # request with /posts will be routed 
                # to the posts-clusterip-srv (service)
                - path: /posts
                  backend: 
                    serviceName: posts-clusterip-srv
                    servicePort: 4000

